make js_preview
hayashi28/protospace pull request #21
Opened 2016-09-30 01:40 UTC by hayashi28

# WHAT
画像のプレビュー機能の実装

# WHY
画像をアップロードした際に、画像のプレビューが見れるようにするため

2016-10-02 13:16 UTC, hc0208 requested changes

2016-10-02 13:16 UTC, hc070208 commented on app/uploaders/avatar_uploader.rb
> +    # "/images/fallback/" + [version_name, "default.png"].compact.join('_')
コメントアウト消しといて

2016-10-02 13:16 UTC, hc070208 commented on app/uploaders/image_uploader.rb
> +    # "/images/fallback/" + [version_name, "default.png"].compact.join('_')
ここも

2016-10-02 13:17 UTC, hc070208 commented
あとはprototypeのeditもね。画像あったらそれが表示されるようにね

2016-10-09 15:14 UTC, ShuheiTsuji commented on app/views/prototypes/_edit_form.html.haml
> +    %span +
改行！

2016-10-09 15:14 UTC, ShuheiTsuji commented on app/views/prototypes/_new_form.html.haml
> +      %span +
改行

2016-10-09 15:18 UTC, ShuheiTsuji commented on app/assets/javascripts/preview.js.coffee
> +          'background-size' : 'cover'
改行

2016-10-09 15:20 UTC, ShuheiTsuji commented
- サブ画像が出てないところ
- editの時に出ないところ

お願い😁

2016-10-09 16:32 UTC, ShuheiTsuji commented
すばらしい！
lgtm

2016-10-09 16:34 UTC, ShuheiTsuji commented
![hayashi_break](https://cloud.githubusercontent.com/assets/16604920/19222002/a8848962-8e89-11e6-8575-126d845844c2.gif)

2016-10-09 16:35 UTC, ShuheiTsuji commented
**ガンガンいこう**😁

2016-10-09 16:36 UTC, SoyaTakahashi commented
まずはgithubのアイコンを設定しよう！

2016-10-09 16:36 UTC, merged